apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ap-south-1b
  labels:
    k8s-addon: storage-aws.addons.k8s.io
parameters:
  type: gp2
  zone: ap-south-1b
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete

