apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: us-west-2b
  labels:
    k8s-addon: storage-aws.addons.k8s.io
parameters:
  type: gp2
  zone: us-west-2b
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete


