apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-demo1
spec:
  baseImage: couchbase/server
  version: enterprise-5.5.1
  authSecret: cb-example-auth
  disableBucketManagement: true
  exposeAdminConsole: true
  adminConsoleServiceType: NodePort
  adminConsoleServices:
    - data
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000
  cluster:
    dataServiceMemoryQuota: 1024
    indexServiceMemoryQuota: 1024
    searchServiceMemoryQuota: 1024
    eventingServiceMemoryQuota: 1024
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  serverGroups:
    - ap-south-1a
    - ap-south-1b
  servers:
    - name: ap-south-1a
      size: 1
      services:
        - data
        - index
        - query
        - search
        - eventing
      serverGroups:
        - ap-south-1a
      pod:
        volumeMounts:
          default: ap-south-1a
          data:  ap-south-1a
          index: ap-south-1a
  volumeClaimTemplates:
    - metadata:
        name: ap-south-1a
      spec:
        storageClassName: "ap-south-1a"
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: ap-south-1b
      spec:
        storageClassName: "ap-south-1b"
        resources:
          requests:
            storage: 5Gi
